//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaInternet.wsPrestamo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enCronograma", Namespace="http://schemas.datacontract.org/2004/07/BancaInternet.EN")]
    [System.SerializableAttribute()]
    public partial class enCronograma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nDiasAtrasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nTotalCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFecVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMontoCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumeroCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSaldoCapitalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nCuota {
            get {
                return this.nCuotaField;
            }
            set {
                if ((this.nCuotaField.Equals(value) != true)) {
                    this.nCuotaField = value;
                    this.RaisePropertyChanged("nCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nDiasAtraso {
            get {
                return this.nDiasAtrasoField;
            }
            set {
                if ((this.nDiasAtrasoField.Equals(value) != true)) {
                    this.nDiasAtrasoField = value;
                    this.RaisePropertyChanged("nDiasAtraso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nTotalCuotas {
            get {
                return this.nTotalCuotasField;
            }
            set {
                if ((this.nTotalCuotasField.Equals(value) != true)) {
                    this.nTotalCuotasField = value;
                    this.RaisePropertyChanged("nTotalCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEstado {
            get {
                return this.sEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.sEstadoField, value) != true)) {
                    this.sEstadoField = value;
                    this.RaisePropertyChanged("sEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFecVencimiento {
            get {
                return this.sFecVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.sFecVencimientoField, value) != true)) {
                    this.sFecVencimientoField = value;
                    this.RaisePropertyChanged("sFecVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaPago {
            get {
                return this.sFechaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.sFechaPagoField, value) != true)) {
                    this.sFechaPagoField = value;
                    this.RaisePropertyChanged("sFechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMontoCuota {
            get {
                return this.sMontoCuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.sMontoCuotaField, value) != true)) {
                    this.sMontoCuotaField = value;
                    this.RaisePropertyChanged("sMontoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumeroCredito {
            get {
                return this.sNumeroCreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNumeroCreditoField, value) != true)) {
                    this.sNumeroCreditoField = value;
                    this.RaisePropertyChanged("sNumeroCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSaldoCapital {
            get {
                return this.sSaldoCapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.sSaldoCapitalField, value) != true)) {
                    this.sSaldoCapitalField = value;
                    this.RaisePropertyChanged("sSaldoCapital");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPrestamo.IwsPrestamo")]
    public interface IwsPrestamo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerCuentasActivasCliente", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerCuentasActivasClienteResponse")]
        BancaInternet.EN.enPrestamo[] WSObtenerCuentasActivasCliente(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerCuentasActivasCliente", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerCuentasActivasClienteResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enPrestamo[]> WSObtenerCuentasActivasClienteAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerDetalleCreditosActivosCliente", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerDetalleCreditosActivosClienteResponse")]
        BancaInternet.EN.enPrestamo WSObtenerDetalleCreditosActivosCliente(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerDetalleCreditosActivosCliente", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerDetalleCreditosActivosClienteResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enPrestamo> WSObtenerDetalleCreditosActivosClienteAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerCronograma", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerCronogramaResponse")]
        BancaInternet.wsPrestamo.enCronograma[] WSObtenerCronograma(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPrestamo/WSObtenerCronograma", ReplyAction="http://tempuri.org/IwsPrestamo/WSObtenerCronogramaResponse")]
        System.Threading.Tasks.Task<BancaInternet.wsPrestamo.enCronograma[]> WSObtenerCronogramaAsync(string sValor1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsPrestamoChannel : BancaInternet.wsPrestamo.IwsPrestamo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsPrestamoClient : System.ServiceModel.ClientBase<BancaInternet.wsPrestamo.IwsPrestamo>, BancaInternet.wsPrestamo.IwsPrestamo {
        
        public IwsPrestamoClient() {
        }
        
        public IwsPrestamoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsPrestamoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPrestamoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPrestamoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaInternet.EN.enPrestamo[] WSObtenerCuentasActivasCliente(string sValor1) {
            return base.Channel.WSObtenerCuentasActivasCliente(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enPrestamo[]> WSObtenerCuentasActivasClienteAsync(string sValor1) {
            return base.Channel.WSObtenerCuentasActivasClienteAsync(sValor1);
        }
        
        public BancaInternet.EN.enPrestamo WSObtenerDetalleCreditosActivosCliente(string sValor1) {
            return base.Channel.WSObtenerDetalleCreditosActivosCliente(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enPrestamo> WSObtenerDetalleCreditosActivosClienteAsync(string sValor1) {
            return base.Channel.WSObtenerDetalleCreditosActivosClienteAsync(sValor1);
        }
        
        public BancaInternet.wsPrestamo.enCronograma[] WSObtenerCronograma(string sValor1) {
            return base.Channel.WSObtenerCronograma(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.wsPrestamo.enCronograma[]> WSObtenerCronogramaAsync(string sValor1) {
            return base.Channel.WSObtenerCronogramaAsync(sValor1);
        }
    }
}
