//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaInternet.wsUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUsuario.IwsUsuario")]
    public interface IwsUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarAsociaconUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarAsociaconUsuarioResponse")]
        int WSRegistrarAsociaconUsuario(string Valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarAsociaconUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarAsociaconUsuarioResponse")]
        System.Threading.Tasks.Task<int> WSRegistrarAsociaconUsuarioAsync(string Valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSCambiarClaveTarjeta", ReplyAction="http://tempuri.org/IwsUsuario/WSCambiarClaveTarjetaResponse")]
        int WSCambiarClaveTarjeta(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSCambiarClaveTarjeta", ReplyAction="http://tempuri.org/IwsUsuario/WSCambiarClaveTarjetaResponse")]
        System.Threading.Tasks.Task<int> WSCambiarClaveTarjetaAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarSeguimientoAccesos", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarSeguimientoAccesosResponse")]
        int WSRegistrarSeguimientoAccesos(BancaInternet.EN.enUsuario poenUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarSeguimientoAccesos", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarSeguimientoAccesosResponse")]
        System.Threading.Tasks.Task<int> WSRegistrarSeguimientoAccesosAsync(BancaInternet.EN.enUsuario poenUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSValidaAccesoHomeBanking", ReplyAction="http://tempuri.org/IwsUsuario/WSValidaAccesoHomeBankingResponse")]
        BancaInternet.EN.enSesion WSValidaAccesoHomeBanking(string valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSValidaAccesoHomeBanking", ReplyAction="http://tempuri.org/IwsUsuario/WSValidaAccesoHomeBankingResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enSesion> WSValidaAccesoHomeBankingAsync(string valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSValidaClaveUnibanca", ReplyAction="http://tempuri.org/IwsUsuario/WSValidaClaveUnibancaResponse")]
        BancaInternet.EN.enUsuarioValida WSValidaClaveUnibanca(string valor1, string valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSValidaClaveUnibanca", ReplyAction="http://tempuri.org/IwsUsuario/WSValidaClaveUnibancaResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUsuarioValida> WSValidaClaveUnibancaAsync(string valor1, string valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSOlvideMiClave", ReplyAction="http://tempuri.org/IwsUsuario/WSOlvideMiClaveResponse")]
        int WSOlvideMiClave(string valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSOlvideMiClave", ReplyAction="http://tempuri.org/IwsUsuario/WSOlvideMiClaveResponse")]
        System.Threading.Tasks.Task<int> WSOlvideMiClaveAsync(string valor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarDatosCliente", ReplyAction="http://tempuri.org/IwsUsuario/WSListarDatosClienteResponse")]
        BancaInternet.EN.enUsuario WSListarDatosCliente(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarDatosCliente", ReplyAction="http://tempuri.org/IwsUsuario/WSListarDatosClienteResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUsuario> WSListarDatosClienteAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSActualizarInformacion", ReplyAction="http://tempuri.org/IwsUsuario/WSActualizarInformacionResponse")]
        bool WSActualizarInformacion(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSActualizarInformacion", ReplyAction="http://tempuri.org/IwsUsuario/WSActualizarInformacionResponse")]
        System.Threading.Tasks.Task<bool> WSActualizarInformacionAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSAfiliacionPaso1ValidacionTarjeta", ReplyAction="http://tempuri.org/IwsUsuario/WSAfiliacionPaso1ValidacionTarjetaResponse")]
        BancaInternet.EN.enUsuario WSAfiliacionPaso1ValidacionTarjeta(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSAfiliacionPaso1ValidacionTarjeta", ReplyAction="http://tempuri.org/IwsUsuario/WSAfiliacionPaso1ValidacionTarjetaResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUsuario> WSAfiliacionPaso1ValidacionTarjetaAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSActualizarSelloSeguridad", ReplyAction="http://tempuri.org/IwsUsuario/WSActualizarSelloSeguridadResponse")]
        string WSActualizarSelloSeguridad(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSActualizarSelloSeguridad", ReplyAction="http://tempuri.org/IwsUsuario/WSActualizarSelloSeguridadResponse")]
        System.Threading.Tasks.Task<string> WSActualizarSelloSeguridadAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarSellos", ReplyAction="http://tempuri.org/IwsUsuario/WSListarSellosResponse")]
        BancaInternet.EN.enSellos[] WSListarSellos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarSellos", ReplyAction="http://tempuri.org/IwsUsuario/WSListarSellosResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enSellos[]> WSListarSellosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSAfiliacionYActualizacionInformacionP2", ReplyAction="http://tempuri.org/IwsUsuario/WSAfiliacionYActualizacionInformacionP2Response")]
        BancaInternet.EN.enUsuarioValida WSAfiliacionYActualizacionInformacionP2(BancaInternet.EN.enUsuario poenUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSAfiliacionYActualizacionInformacionP2", ReplyAction="http://tempuri.org/IwsUsuario/WSAfiliacionYActualizacionInformacionP2Response")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUsuarioValida> WSAfiliacionYActualizacionInformacionP2Async(BancaInternet.EN.enUsuario poenUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsUsuarioChannel : BancaInternet.wsUsuario.IwsUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsUsuarioClient : System.ServiceModel.ClientBase<BancaInternet.wsUsuario.IwsUsuario>, BancaInternet.wsUsuario.IwsUsuario {
        
        public IwsUsuarioClient() {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int WSRegistrarAsociaconUsuario(string Valor1) {
            return base.Channel.WSRegistrarAsociaconUsuario(Valor1);
        }
        
        public System.Threading.Tasks.Task<int> WSRegistrarAsociaconUsuarioAsync(string Valor1) {
            return base.Channel.WSRegistrarAsociaconUsuarioAsync(Valor1);
        }
        
        public int WSCambiarClaveTarjeta(string sValor1) {
            return base.Channel.WSCambiarClaveTarjeta(sValor1);
        }
        
        public System.Threading.Tasks.Task<int> WSCambiarClaveTarjetaAsync(string sValor1) {
            return base.Channel.WSCambiarClaveTarjetaAsync(sValor1);
        }
        
        public int WSRegistrarSeguimientoAccesos(BancaInternet.EN.enUsuario poenUsuario) {
            return base.Channel.WSRegistrarSeguimientoAccesos(poenUsuario);
        }
        
        public System.Threading.Tasks.Task<int> WSRegistrarSeguimientoAccesosAsync(BancaInternet.EN.enUsuario poenUsuario) {
            return base.Channel.WSRegistrarSeguimientoAccesosAsync(poenUsuario);
        }
        
        public BancaInternet.EN.enSesion WSValidaAccesoHomeBanking(string valor1) {
            return base.Channel.WSValidaAccesoHomeBanking(valor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enSesion> WSValidaAccesoHomeBankingAsync(string valor1) {
            return base.Channel.WSValidaAccesoHomeBankingAsync(valor1);
        }
        
        public BancaInternet.EN.enUsuarioValida WSValidaClaveUnibanca(string valor1, string valor2) {
            return base.Channel.WSValidaClaveUnibanca(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUsuarioValida> WSValidaClaveUnibancaAsync(string valor1, string valor2) {
            return base.Channel.WSValidaClaveUnibancaAsync(valor1, valor2);
        }
        
        public int WSOlvideMiClave(string valor1) {
            return base.Channel.WSOlvideMiClave(valor1);
        }
        
        public System.Threading.Tasks.Task<int> WSOlvideMiClaveAsync(string valor1) {
            return base.Channel.WSOlvideMiClaveAsync(valor1);
        }
        
        public BancaInternet.EN.enUsuario WSListarDatosCliente(string sValor1) {
            return base.Channel.WSListarDatosCliente(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUsuario> WSListarDatosClienteAsync(string sValor1) {
            return base.Channel.WSListarDatosClienteAsync(sValor1);
        }
        
        public bool WSActualizarInformacion(string sValor1) {
            return base.Channel.WSActualizarInformacion(sValor1);
        }
        
        public System.Threading.Tasks.Task<bool> WSActualizarInformacionAsync(string sValor1) {
            return base.Channel.WSActualizarInformacionAsync(sValor1);
        }
        
        public BancaInternet.EN.enUsuario WSAfiliacionPaso1ValidacionTarjeta(string sValor1) {
            return base.Channel.WSAfiliacionPaso1ValidacionTarjeta(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUsuario> WSAfiliacionPaso1ValidacionTarjetaAsync(string sValor1) {
            return base.Channel.WSAfiliacionPaso1ValidacionTarjetaAsync(sValor1);
        }
        
        public string WSActualizarSelloSeguridad(string sValor1) {
            return base.Channel.WSActualizarSelloSeguridad(sValor1);
        }
        
        public System.Threading.Tasks.Task<string> WSActualizarSelloSeguridadAsync(string sValor1) {
            return base.Channel.WSActualizarSelloSeguridadAsync(sValor1);
        }
        
        public BancaInternet.EN.enSellos[] WSListarSellos() {
            return base.Channel.WSListarSellos();
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enSellos[]> WSListarSellosAsync() {
            return base.Channel.WSListarSellosAsync();
        }
        
        public BancaInternet.EN.enUsuarioValida WSAfiliacionYActualizacionInformacionP2(BancaInternet.EN.enUsuario poenUsuario) {
            return base.Channel.WSAfiliacionYActualizacionInformacionP2(poenUsuario);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUsuarioValida> WSAfiliacionYActualizacionInformacionP2Async(BancaInternet.EN.enUsuario poenUsuario) {
            return base.Channel.WSAfiliacionYActualizacionInformacionP2Async(poenUsuario);
        }
    }
}
