//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaInternet.wsDescripcion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDescripcion.IwsDescripcion")]
    public interface IwsDescripcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSListarValoresParametros", ReplyAction="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosResponse")]
        BancaInternet.EN.enDescripcion[] WSListarValoresParametros(int iIdDominio, bool bCerrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSListarValoresParametros", ReplyAction="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enDescripcion[]> WSListarValoresParametrosAsync(int iIdDominio, bool bCerrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSObtenerArchivosHomeBanking", ReplyAction="http://tempuri.org/IwsDescripcion/WSObtenerArchivosHomeBankingResponse")]
        string[] WSObtenerArchivosHomeBanking(int iValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSObtenerArchivosHomeBanking", ReplyAction="http://tempuri.org/IwsDescripcion/WSObtenerArchivosHomeBankingResponse")]
        System.Threading.Tasks.Task<string[]> WSObtenerArchivosHomeBankingAsync(int iValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosSiscredinka", ReplyAction="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosSiscredinkaResponse")]
        BancaInternet.EN.enDescripcionSiscredinka[] WSListarValoresParametrosSiscredinka(int iValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosSiscredinka", ReplyAction="http://tempuri.org/IwsDescripcion/WSListarValoresParametrosSiscredinkaResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSListarValoresParametrosSiscredinkaAsync(int iValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSBusquedaActividadesEconomicasCIIU", ReplyAction="http://tempuri.org/IwsDescripcion/WSBusquedaActividadesEconomicasCIIUResponse")]
        BancaInternet.EN.enDescripcionSiscredinka[] WSBusquedaActividadesEconomicasCIIU(string sValor1, string sValor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSBusquedaActividadesEconomicasCIIU", ReplyAction="http://tempuri.org/IwsDescripcion/WSBusquedaActividadesEconomicasCIIUResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSBusquedaActividadesEconomicasCIIUAsync(string sValor1, string sValor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSAfiliacionBusquedaActividadesCIIU", ReplyAction="http://tempuri.org/IwsDescripcion/WSAfiliacionBusquedaActividadesCIIUResponse")]
        BancaInternet.EN.enDescripcionSiscredinka[] WSAfiliacionBusquedaActividadesCIIU(string sValor1, string sValor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDescripcion/WSAfiliacionBusquedaActividadesCIIU", ReplyAction="http://tempuri.org/IwsDescripcion/WSAfiliacionBusquedaActividadesCIIUResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSAfiliacionBusquedaActividadesCIIUAsync(string sValor1, string sValor2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsDescripcionChannel : BancaInternet.wsDescripcion.IwsDescripcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsDescripcionClient : System.ServiceModel.ClientBase<BancaInternet.wsDescripcion.IwsDescripcion>, BancaInternet.wsDescripcion.IwsDescripcion {
        
        public IwsDescripcionClient() {
        }
        
        public IwsDescripcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsDescripcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsDescripcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsDescripcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaInternet.EN.enDescripcion[] WSListarValoresParametros(int iIdDominio, bool bCerrar) {
            return base.Channel.WSListarValoresParametros(iIdDominio, bCerrar);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enDescripcion[]> WSListarValoresParametrosAsync(int iIdDominio, bool bCerrar) {
            return base.Channel.WSListarValoresParametrosAsync(iIdDominio, bCerrar);
        }
        
        public string[] WSObtenerArchivosHomeBanking(int iValor1) {
            return base.Channel.WSObtenerArchivosHomeBanking(iValor1);
        }
        
        public System.Threading.Tasks.Task<string[]> WSObtenerArchivosHomeBankingAsync(int iValor1) {
            return base.Channel.WSObtenerArchivosHomeBankingAsync(iValor1);
        }
        
        public BancaInternet.EN.enDescripcionSiscredinka[] WSListarValoresParametrosSiscredinka(int iValor1) {
            return base.Channel.WSListarValoresParametrosSiscredinka(iValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSListarValoresParametrosSiscredinkaAsync(int iValor1) {
            return base.Channel.WSListarValoresParametrosSiscredinkaAsync(iValor1);
        }
        
        public BancaInternet.EN.enDescripcionSiscredinka[] WSBusquedaActividadesEconomicasCIIU(string sValor1, string sValor2) {
            return base.Channel.WSBusquedaActividadesEconomicasCIIU(sValor1, sValor2);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSBusquedaActividadesEconomicasCIIUAsync(string sValor1, string sValor2) {
            return base.Channel.WSBusquedaActividadesEconomicasCIIUAsync(sValor1, sValor2);
        }
        
        public BancaInternet.EN.enDescripcionSiscredinka[] WSAfiliacionBusquedaActividadesCIIU(string sValor1, string sValor2) {
            return base.Channel.WSAfiliacionBusquedaActividadesCIIU(sValor1, sValor2);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSAfiliacionBusquedaActividadesCIIUAsync(string sValor1, string sValor2) {
            return base.Channel.WSAfiliacionBusquedaActividadesCIIUAsync(sValor1, sValor2);
        }
    }
}
