//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaInternet.wsUbigeo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUbigeo.IwsUbigeo")]
    public interface IwsUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerDepartamentos", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerDepartamentosResponse")]
        BancaInternet.EN.enUbigeo[] WSObtenerDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerDepartamentos", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerDepartamentosResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerProvinciaPorDepartamentos", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerProvinciaPorDepartamentosResponse")]
        BancaInternet.EN.enUbigeo[] WSObtenerProvinciaPorDepartamentos(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerProvinciaPorDepartamentos", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerProvinciaPorDepartamentosResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerProvinciaPorDepartamentosAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerDistritosPorProvincia", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerDistritosPorProvinciaResponse")]
        BancaInternet.EN.enUbigeo[] WSObtenerDistritosPorProvincia(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSObtenerDistritosPorProvincia", ReplyAction="http://tempuri.org/IwsUbigeo/WSObtenerDistritosPorProvinciaResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerDistritosPorProvinciaAsync(string sValor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSAfiliacionBusquedaUbigeo", ReplyAction="http://tempuri.org/IwsUbigeo/WSAfiliacionBusquedaUbigeoResponse")]
        BancaInternet.EN.enDescripcionSiscredinka[] WSAfiliacionBusquedaUbigeo(string sValor1, string sValor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUbigeo/WSAfiliacionBusquedaUbigeo", ReplyAction="http://tempuri.org/IwsUbigeo/WSAfiliacionBusquedaUbigeoResponse")]
        System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSAfiliacionBusquedaUbigeoAsync(string sValor1, string sValor2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsUbigeoChannel : BancaInternet.wsUbigeo.IwsUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsUbigeoClient : System.ServiceModel.ClientBase<BancaInternet.wsUbigeo.IwsUbigeo>, BancaInternet.wsUbigeo.IwsUbigeo {
        
        public IwsUbigeoClient() {
        }
        
        public IwsUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancaInternet.EN.enUbigeo[] WSObtenerDepartamentos() {
            return base.Channel.WSObtenerDepartamentos();
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerDepartamentosAsync() {
            return base.Channel.WSObtenerDepartamentosAsync();
        }
        
        public BancaInternet.EN.enUbigeo[] WSObtenerProvinciaPorDepartamentos(string sValor1) {
            return base.Channel.WSObtenerProvinciaPorDepartamentos(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerProvinciaPorDepartamentosAsync(string sValor1) {
            return base.Channel.WSObtenerProvinciaPorDepartamentosAsync(sValor1);
        }
        
        public BancaInternet.EN.enUbigeo[] WSObtenerDistritosPorProvincia(string sValor1) {
            return base.Channel.WSObtenerDistritosPorProvincia(sValor1);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enUbigeo[]> WSObtenerDistritosPorProvinciaAsync(string sValor1) {
            return base.Channel.WSObtenerDistritosPorProvinciaAsync(sValor1);
        }
        
        public BancaInternet.EN.enDescripcionSiscredinka[] WSAfiliacionBusquedaUbigeo(string sValor1, string sValor2) {
            return base.Channel.WSAfiliacionBusquedaUbigeo(sValor1, sValor2);
        }
        
        public System.Threading.Tasks.Task<BancaInternet.EN.enDescripcionSiscredinka[]> WSAfiliacionBusquedaUbigeoAsync(string sValor1, string sValor2) {
            return base.Channel.WSAfiliacionBusquedaUbigeoAsync(sValor1, sValor2);
        }
    }
}
